<?php
/**
 * ObjSaveOption
 *
 * PHP version 5
 *
 * @category Class
 * @package  Aspose\ThreeD\Cloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Aspose\ThreeD\Cloud\Model;
use \Aspose\ThreeD\Cloud\ObjectSerializer;

/**
 * ObjSaveOption Class Doc Comment
 *
 * @category Class
 * @package  Aspose\ThreeD\Cloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ObjSaveOption extends SaveOptions 
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ObjSaveOption';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'verbose' => 'bool',
        'serialize_w' => 'bool',
        'enable_materials' => 'bool',
        'flip_coordinate_system' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'verbose' => null,
        'serialize_w' => null,
        'enable_materials' => null,
        'flip_coordinate_system' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats + parent::swaggerFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'verbose' => 'Verbose',
        'serialize_w' => 'SerializeW',
        'enable_materials' => 'EnableMaterials',
        'flip_coordinate_system' => 'FlipCoordinateSystem'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'verbose' => 'setVerbose',
        'serialize_w' => 'setSerializeW',
        'enable_materials' => 'setEnableMaterials',
        'flip_coordinate_system' => 'setFlipCoordinateSystem'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'verbose' => 'getVerbose',
        'serialize_w' => 'getSerializeW',
        'enable_materials' => 'getEnableMaterials',
        'flip_coordinate_system' => 'getFlipCoordinateSystem'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    


    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['verbose'] = isset($data['verbose']) ? $data['verbose'] : null;
        $this->container['serialize_w'] = isset($data['serialize_w']) ? $data['serialize_w'] : null;
        $this->container['enable_materials'] = isset($data['enable_materials']) ? $data['enable_materials'] : null;
        $this->container['flip_coordinate_system'] = isset($data['flip_coordinate_system']) ? $data['flip_coordinate_system'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        if (!parent::valid()) {
            return false;
        }

        return true;
    }


    /**
     * Gets verbose
     *
     * @return bool
     */
    public function getVerbose()
    {
        return $this->container['verbose'];
    }

    /**
     * Sets verbose
     *
     * @param bool $verbose Gets or sets whether generate comments for each section.
     *
     * @return $this
     */
    public function setVerbose($verbose)
    {
        $this->container['verbose'] = $verbose;

        return $this;
    }

    /**
     * Gets serialize_w
     *
     * @return bool
     */
    public function getSerializeW()
    {
        return $this->container['serialize_w'];
    }

    /**
     * Sets serialize_w
     *
     * @param bool $serialize_w Gets or sets whether serialize W component in model's vertex position.
     *
     * @return $this
     */
    public function setSerializeW($serialize_w)
    {
        $this->container['serialize_w'] = $serialize_w;

        return $this;
    }

    /**
     * Gets enable_materials
     *
     * @return bool
     */
    public function getEnableMaterials()
    {
        return $this->container['enable_materials'];
    }

    /**
     * Sets enable_materials
     *
     * @param bool $enable_materials Gets or sets whether import/export materials for each object.
     *
     * @return $this
     */
    public function setEnableMaterials($enable_materials)
    {
        $this->container['enable_materials'] = $enable_materials;

        return $this;
    }

    /**
     * Gets flip_coordinate_system
     *
     * @return bool
     */
    public function getFlipCoordinateSystem()
    {
        return $this->container['flip_coordinate_system'];
    }

    /**
     * Sets flip_coordinate_system
     *
     * @param bool $flip_coordinate_system Gets or sets whether flip coordinate system of control points/normal during importing/exporting.
     *
     * @return $this
     */
    public function setFlipCoordinateSystem($flip_coordinate_system)
    {
        $this->container['flip_coordinate_system'] = $flip_coordinate_system;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


