<?php
/**
 * PdfLightingScheme
 *
 * PHP version 5
 *
 * @category Class
 * @package  Aspose\ThreeD\Cloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Aspose\ThreeD\Cloud\Model;
use \Aspose\ThreeD\Cloud\ObjectSerializer;

/**
 * PdfLightingScheme Class Doc Comment
 *
 * @category Class
 * @description Render mode specifies the style in which the 3D artwork is rendered.
 * @package  Aspose\ThreeD\Cloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PdfLightingScheme
{
    /**
     * Possible values of this enum
     */
    const Artwork = 0;
    const None = 1;
    const White = 2;
    const Day = 3;
    const Night = 4;
    const Hard = 5;
    const Primary = 6;
    const Blue = 7;
    const Red = 8;
    const Cube = 9;
    const CAD = 10;
    const Headlamp = 11;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::Artwork,
            self::None,
            self::White,
            self::Day,
            self::Night,
            self::Hard,
            self::Primary,
            self::Blue,
            self::Red,
            self::Cube,
            self::CAD,
            self::Headlamp,
        ];
    }
}


