<?php
/**
 * Sphere
 *
 * PHP version 5
 *
 * @category Class
 * @package  Aspose\ThreeD\Cloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Aspose\ThreeD\Cloud\Model;

use \ArrayAccess;
use \Aspose\ThreeD\Cloud\ObjectSerializer;

/**
 * Sphere Class Doc Comment
 *
 * @category Class
 * @description The Sphere Entity
 * @package  Aspose\ThreeD\Cloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Sphere implements  ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Sphere';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'name' => 'string',
        'width_segments' => 'int',
        'height_segments' => 'int',
        'phi_start' => 'double',
        'phi_length' => 'double',
        'theta_start' => 'double',
        'theta_length' => 'double',
        'radius' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'name' => null,
        'width_segments' => 'int32',
        'height_segments' => 'int32',
        'phi_start' => 'double',
        'phi_length' => 'double',
        'theta_start' => 'double',
        'theta_length' => 'double',
        'radius' => 'double'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'Name',
        'width_segments' => 'WidthSegments',
        'height_segments' => 'HeightSegments',
        'phi_start' => 'PhiStart',
        'phi_length' => 'PhiLength',
        'theta_start' => 'ThetaStart',
        'theta_length' => 'ThetaLength',
        'radius' => 'Radius'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'width_segments' => 'setWidthSegments',
        'height_segments' => 'setHeightSegments',
        'phi_start' => 'setPhiStart',
        'phi_length' => 'setPhiLength',
        'theta_start' => 'setThetaStart',
        'theta_length' => 'setThetaLength',
        'radius' => 'setRadius'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'width_segments' => 'getWidthSegments',
        'height_segments' => 'getHeightSegments',
        'phi_start' => 'getPhiStart',
        'phi_length' => 'getPhiLength',
        'theta_start' => 'getThetaStart',
        'theta_length' => 'getThetaLength',
        'radius' => 'getRadius'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['width_segments'] = isset($data['width_segments']) ? $data['width_segments'] : null;
        $this->container['height_segments'] = isset($data['height_segments']) ? $data['height_segments'] : null;
        $this->container['phi_start'] = isset($data['phi_start']) ? $data['phi_start'] : null;
        $this->container['phi_length'] = isset($data['phi_length']) ? $data['phi_length'] : null;
        $this->container['theta_start'] = isset($data['theta_start']) ? $data['theta_start'] : null;
        $this->container['theta_length'] = isset($data['theta_length']) ? $data['theta_length'] : null;
        $this->container['radius'] = isset($data['radius']) ? $data['radius'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['width_segments'] === null) {
            $invalidProperties[] = "'width_segments' can't be null";
        }
        if ($this->container['height_segments'] === null) {
            $invalidProperties[] = "'height_segments' can't be null";
        }
        if ($this->container['phi_start'] === null) {
            $invalidProperties[] = "'phi_start' can't be null";
        }
        if ($this->container['phi_length'] === null) {
            $invalidProperties[] = "'phi_length' can't be null";
        }
        if ($this->container['theta_start'] === null) {
            $invalidProperties[] = "'theta_start' can't be null";
        }
        if ($this->container['theta_length'] === null) {
            $invalidProperties[] = "'theta_length' can't be null";
        }
        if ($this->container['radius'] === null) {
            $invalidProperties[] = "'radius' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['width_segments'] === null) {
            return false;
        }
        if ($this->container['height_segments'] === null) {
            return false;
        }
        if ($this->container['phi_start'] === null) {
            return false;
        }
        if ($this->container['phi_length'] === null) {
            return false;
        }
        if ($this->container['theta_start'] === null) {
            return false;
        }
        if ($this->container['theta_length'] === null) {
            return false;
        }
        if ($this->container['radius'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Gets or sets the Name of Sphere.
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets width_segments
     *
     * @return int
     */
    public function getWidthSegments()
    {
        return $this->container['width_segments'];
    }

    /**
     * Sets width_segments
     *
     * @param int $width_segments Gets or sets the width segments.
     *
     * @return $this
     */
    public function setWidthSegments($width_segments)
    {
        $this->container['width_segments'] = $width_segments;

        return $this;
    }

    /**
     * Gets height_segments
     *
     * @return int
     */
    public function getHeightSegments()
    {
        return $this->container['height_segments'];
    }

    /**
     * Sets height_segments
     *
     * @param int $height_segments Gets or sets the height segments.
     *
     * @return $this
     */
    public function setHeightSegments($height_segments)
    {
        $this->container['height_segments'] = $height_segments;

        return $this;
    }

    /**
     * Gets phi_start
     *
     * @return double
     */
    public function getPhiStart()
    {
        return $this->container['phi_start'];
    }

    /**
     * Sets phi_start
     *
     * @param double $phi_start Gets or sets the phi start.
     *
     * @return $this
     */
    public function setPhiStart($phi_start)
    {
        $this->container['phi_start'] = $phi_start;

        return $this;
    }

    /**
     * Gets phi_length
     *
     * @return double
     */
    public function getPhiLength()
    {
        return $this->container['phi_length'];
    }

    /**
     * Sets phi_length
     *
     * @param double $phi_length Gets or sets the length of the phi.
     *
     * @return $this
     */
    public function setPhiLength($phi_length)
    {
        $this->container['phi_length'] = $phi_length;

        return $this;
    }

    /**
     * Gets theta_start
     *
     * @return double
     */
    public function getThetaStart()
    {
        return $this->container['theta_start'];
    }

    /**
     * Sets theta_start
     *
     * @param double $theta_start Gets or sets the theta start.
     *
     * @return $this
     */
    public function setThetaStart($theta_start)
    {
        $this->container['theta_start'] = $theta_start;

        return $this;
    }

    /**
     * Gets theta_length
     *
     * @return double
     */
    public function getThetaLength()
    {
        return $this->container['theta_length'];
    }

    /**
     * Sets theta_length
     *
     * @param double $theta_length Gets or sets the length of the theta.
     *
     * @return $this
     */
    public function setThetaLength($theta_length)
    {
        $this->container['theta_length'] = $theta_length;

        return $this;
    }

    /**
     * Gets radius
     *
     * @return double
     */
    public function getRadius()
    {
        return $this->container['radius'];
    }

    /**
     * Sets radius
     *
     * @param double $radius Gets or sets the radius
     *
     * @return $this
     */
    public function setRadius($radius)
    {
        $this->container['radius'] = $radius;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


